# Generated by Django 4.1.3 on 2022-12-26 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_product_category_remove_product_unit_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='product',
        ),
    ]
