# Generated by Django 3.2.16 on 2022-12-27 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_product_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='total_price',
        ),
    ]
