# Generated by Django 3.2.16 on 2022-12-27 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_remove_product_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='mount',
        ),
        migrations.AddField(
            model_name='product',
            name='amount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
