# Generated by Django 3.2.16 on 2022-12-31 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_alter_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
