# Generated by Django 4.1.4 on 2023-01-03 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jabama', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='acomodation',
            name='avail',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='acomodation',
            name='create',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='acomodation',
            name='desc',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='acomodation',
            name='discount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='acomodation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='acomodation'),
        ),
        migrations.AddField(
            model_name='acomodation',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='acomodation',
            name='total_price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='acomodation',
            name='update',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
